name: Continuous integration

on:
  push:
    branches:
      - master
      - "releases/**"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
  page_build:
  release:
    types:
      - created

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} @ ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install requirements
        run: |
          pip install -U pip setuptools wheel build
          pip install pytest pytest-benchmark pytest-cov

      - name: Build extensions
        run: |
          pip install -v .

      - name: Run tests
        run: |
          pytest -v --benchmark-disable --log-cli-level=info -k 'not highway' tests
